### ISSUE TITLE
为什么既有 MultiStrategy，又有 F1MultiStrategy?

### ISSUE THREAD

**Issue by dyan0123** [zdqreg/alphalib-discussions#1]
## 问题类型
- [ ] 文档相关

## 描述
1、我看base_strategy.py 文件里，有 class MultiStrategy。
2、我看f1_strategy.py 文件里，有 F1MultiStrategy。

感觉两个有重复，发现只有legacy文件夹的adaptv3_example.py 用了 MultiStrategy。如果不想要legecy，是不是完全可以忽略 base_strategy.py 文件里的 class MultiStrategy？

## 截图
<img width="695" alt="1717077354156" src="https://github.com/zdqreg/alphalib-discussions/assets/19541628/f738c2ad-b063-43f7-8826-065349e67be7">

<img width="690" alt="1717077395997" src="https://github.com/zdqreg/alphalib-discussions/assets/19541628/9a8daedf-f9b7-4715-ab54-d03fc8980f98">

**Comment by zdqreg** [comment]
BaseStrategy相当于z1的范式，不需要受到f1范式的限制，只要输出alloc_ratio就能回放。
MultiStrategy支持任意BaseStrategy的组合，假设通过内部alloc_ratio控制权重，因此没提供额外的权重参数。

F1Strategy是一个样例，演示如何在z1范式下复现f1的结果。
F1MultiStrategy是茄哥加的，可以直接在子策略上配置权重，据说更符合古法用户习惯。

F1StrategyLegacy是匹配F1实盘的配置格式，严格来说实盘代码不算是F1范式，在F1出来之前就差不多这个样子。后面确实可以考虑删了。

**Comment by dyan0123** [comment]
已经弄清楚了
