### ISSUE TITLE
某symbol早已下架，但 start_date 在这之后的bug

### ISSUE THREAD

**Issue by dyan0123** [zdqreg/alphalib-discussions#2]
## 问题类型
- [x] Bug 反馈

## 描述
z1设置start_date 在以下时候有效：
1）可以在某symbol仍然可交易（start_date落在 dataframe区间）
2）start_date在某 symbol 上架之前（start_date对应的start_idx 等于0）

以下时候失效，拦不住下架symbol：
2）start_date 设置为某symbol下架之后的时间

## 复现步骤
如果适用，请描述复现问题的步骤，包括：
可以用cocos复现。此symbol 2023-05-24 22:00:00 下架，start_date设置为 '2023-09-01'。 改以下2处：
![ksnip_20240531-090502](https://github.com/zdqreg/alphalib-discussions/assets/19541628/6675d48e-fab6-4abf-8b83-ef3994063493)

运行结果如下：
![ksnip_20240531-091902](https://github.com/zdqreg/alphalib-discussions/assets/19541628/a1821bd6-79a3-4c48-982a-73b3904f1e9e)
==========================
==========================
![ksnip_20240531-092309](https://github.com/zdqreg/alphalib-discussions/assets/19541628/d904479a-eec2-4b73-be63-d70487ff5a8b)

从上图可见：一共读出来1218行的dataframe，但 start_date在最大时间之后，所以 start_idx 也是1218。经过max 那一行，变成了1206，反而读出来部分下架symbol。后面传到 filter_handle_before之前，咔咔咔一路没拦住。

## 解决办法
![ksnip_20240531-092819](https://github.com/zdqreg/alphalib-discussions/assets/19541628/fa94fc37-6a43-409f-9b49-a8cd75dd4819)
把注释的代码打开，提前判断一下。

**Comment by zdqreg** [comment]
这个问题我之前发现了，不过按我理解，只是有一些冗余计算，但不影响alloc_ratio的计算结果吧？最终返回前会做筛选的

**Comment by dyan0123** [comment]
如果只有一个cocos就拦不住。但有多个symbol，max_time就不是cocos的了，后面也能拦住，不影响结果。

**Comment by dyan0123** [comment]
> 这个问题我之前发现了，不过按我理解，只是有一些冗余计算，但不影响alloc_ratio的计算结果吧？最终返回前会做筛选的

你说得对。其实不影响的。如果只有一个cocos就拦不住。但有多个symbol，max_time就不是cocos的了，后面也能拦住，不影响结果。

**Comment by zdqreg** [comment]
> > 这个问题我之前发现了，不过按我理解，只是有一些冗余计算，但不影响alloc_ratio的计算结果吧？最终返回前会做筛选的
> 
> 你说得对。其实不影响的。如果只有一个cocos就拦不住。但有多个symbol，max_time就不是cocos的了，后面也能拦住，不影响结果。

哦对，确实应该改一下
