### ISSUE TITLE
hold_hour导致初始周期有多余的symbol的bug

### ISSUE THREAD

**Issue by dyan0123** [zdqreg/alphalib-discussions#7]
## 问题类型
- [x] Bug 反馈

## 描述
比如设置 start_date = '2023-09-01', 但真实分配 alloc_ratio 会比这早hold_hour个周期。在rolling的话，导致真实设置的第一个周期会有更早周期的symbol。导致稍有不准。

## 复现步骤
只要hold_hour 不设置成1，随便怎么配都能复现。我是如下：
![ksnip_20240603-154437](https://github.com/zdqreg/alphalib-discussions/assets/19541628/aa0d8c7b-757d-4ef9-b999-4956bd477077)

在如下位置打印：
![ksnip_20240603-154613](https://github.com/zdqreg/alphalib-discussions/assets/19541628/e275af5e-b13b-4697-94cf-cf11625e3a55)

发现，2023-09-01 00:00:00 是第一个周期，应该只有多空共2个symbol，但是居然有4个。因为 2023-08-31 23:00:00 这个周期还有更早的hold_hour 全都被选出了，而且分配了不为0的alloc_ratio。

就是如下代码影响的：
![ksnip_20240603-154904](https://github.com/zdqreg/alphalib-discussions/assets/19541628/450b1272-74a8-4c5f-bd67-2e7ec6b6658f)
因为 select_long_inds和select_short_inds 也包括 start_idx = max(start_idx - self.strategy_config.hold_period, 0) 这段。在rolling就会向下影响。解决方法就是把注释打开，在手动给恢复为0。

回测结果其实相差不大，因为也就前面几个周期影响。

**Comment by zdqreg** [comment]
这个和f1的回测/实盘不一致吗？能否提供对比f1 vs z1的代码？

**Comment by dyan0123** [comment]
> 这个和f1的回测/实盘不一致吗？能否提供对比f1 vs z1的代码？

我试了。您原版和f1 是一样的，我改完反而和f1不一样。
