### ISSUE TITLE
calc_alloc_ratio 提速探讨

### ISSUE THREAD

**Issue by unowjx2022** [zdqreg/alphalib-discussions#8]
# Issue

根据性能分析日志反馈（如下图），calc_alloc_ratio 占用了很大的时间，因此想面向 calc_alloc_ratio 进行时间提速方面的探讨。
![image](https://github.com/zdqreg/alphalib-discussions/assets/107868593/c7b686da-c167-45b0-9c39-dccb5fb3a0bc)

## 问题类型
- [ ] Bug 反馈
- [ ] 功能请求
- [x] 性能问题
- [ ] 文档相关
- [ ] 其他

## 描述
在炼丹场景下，需要进行 36(个月) * 20(次) * 4000(轮) 的 z1 滚动回放，每次回放的策略为10个以上的策略组合，因此想请教 z神 可以在哪些方面进行提速优化（减少时间开销）。

## 复现步骤
请参考Issue中的图，图示是 bias_multi.py 的性能分析日志，左侧数字为单步骤时间开销。

## 预期行为
能否指点一些优化方向进行提速处理。

## 代码
无

## 截图
如上图

## 环境信息
- Python版本：Python 3.11.4
- Python库版本：与`requirements.txt`一致
- 操作系统：Linux Ubuntu 20.04

## 其他上下文
无

**Comment by zdqreg** [comment]
可以考虑重写一个Strategy类，在上层计算好因子传进去，这样可以在上层做去重+并行。或者也可以在里面加一些缓存机制避免重复计算。

**Comment by unowjx2022** [comment]
okk，这两天已经在这样设计，谢谢z神回复～
